### ISSUE TITLE
Generator throws an exception when rerun with new test data

### ISSUE THREAD

**Issue by alexanderkotsev** [INSPIRE-MIF/caniuse#23]
I suspect that this relates to the new tools being added (following tests with ESRI tools). @thorsten-reitz - can you please have a look.

The error is below:

```./caniuse_generator.rb ../results > out.html
Traceback (most recent call last):
	5: from ./caniuse_generator.rb:5:in `<main>'
	4: from /root/caniuse/generator/src/generator.rb:16:in `parse_data'
	3: from /root/caniuse/generator/src/generator.rb:16:in `foreach'
	2: from /root/caniuse/generator/src/generator.rb:18:in `block in parse_data'
	1: from /usr/lib/ruby/2.5.0/json/common.rb:156:in `parse'
 (JSON::ParserError)json/common.rb:156:in `parse': 765: unexpected token at ....

**Comment by thorsten-reitz** [comment]
Hi @alexanderkotsev I can confirm the issue. It is caused by the file `GML.Tests-ArcGIS.Pro_DIE.v2.3.json` not being valid json. Specifically, it contains invalid quote marks:

```
"notes”:”used with the Data Interoperability Extension",
```

**Comment by thorsten-reitz** [comment]
Github actualy marks the error:

https://github.com/INSPIRE-MIF/caniuse/blob/master/results/GML.Tests-ArcGIS.Pro_DIE.v2.3.json

Makes me think I should add a Linter to this repository.

**Comment by alexanderkotsev** [comment]
Fixed after linting the JSON files with results. Thanks!

**Comment by alexanderkotsev** [comment]
The generator works now, but there is some issue with the different tests being mixed (GeoJSON tests being provided together with GML tests). Also, the length of the columns in the table is different. I tried to fix this manually in the repository. Attached here - the actual output of the test.....
[out.html.zip](https://github.com/INSPIRE-MIF/caniuse/files/3340046/out.html.zip)
